// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnkckyvjqdpgckslumrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRua2NreXZqcWRwZ2Nrc2x1bXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2OTQ0OTQsImV4cCI6MjA5NDI3MDQ5NH0.4XDGFn-2rQjDhKo-fAQVX_youVkmQptCx0Sn9I7rUMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});